AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'vendor/**/*'
  - 'gemfiles/vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

