name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Release Gem
      id: release-gem
      uses: salsify/action-release-gem@76815459482984159ec020def58da8aed594e618
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
